### ISSUE TITLE
Add teacher subject is not updated to table ( via add dialog)

### ISSUE THREAD

**Issue by Gopigovind** [kd-school-erp/erp-ui#258]
Add teacher subject is not updated to table ( via add dialog)
		1. teacher page
		2. click add icon in grid header
		3. fill all fields and click add
		4. After closed the popup, the subject field is not updated in grid UI
		
2. Grid name fields values are hided, when type more than 10 char ( we need to set auto width)

![image](https://user-images.githubusercontent.com/60418235/230432737-7e157f51-2b34-443c-b432-45d843fbdac9.png)

**Comment by ArunprasadRajendran** [comment]
![Screenshot (320)](https://user-images.githubusercontent.com/30168649/230715258-f3c13e35-f3fa-46bc-a046-64cdbec5c3e3.png)
