### ISSUE TITLE
Admin-student-Edit student is not working

### ISSUE THREAD

**Issue by Gopigovind** [kd-school-erp/erp-ui#262]
Edit student is not working (same usecase teacher also)
		1. click add button 
		2. fill fields and add
		3. click edit icon and change to surname value
		4. press save - API failured and error

**Comment by ArunprasadRajendran** [comment]
while editing the recently added record this issue happens because we are not getting the record from db instead of that we are manually adding the record on that we don't have id in our hand. this issue happens across all the pages
