### ISSUE TITLE
Attendance issues

### ISSUE THREAD

**Issue by Jenita** [kd-school-erp/erp-ui#270]
Attendance:
Student Attendance
No data displayed for student attendance even class mapped for student .from backend
For Date column value  is not displayed
Teacher Attendance:
In attendance sheet Teacher name is not displayed.
For Date column value  is not displayed

staff Attendance:
In attendance sheet staff name is not displayed.
For Date column value  is not displayed

**Comment by Jenita** [comment]
![image](https://user-images.githubusercontent.com/4198869/230706150-23d72a74-357c-4852-a4c2-f5a920512100.png)
 in student attendance surname is displayed , Update to first and last name

**Comment by Gopigovind** [comment]
Hi @Jenita , 

![image](https://user-images.githubusercontent.com/60418235/230707759-9b0b444f-65f2-4c6a-8956-228e01446b4d.png)

In backend API returned null value for date field, so the date is not displayed. 

Regards,
Gopi G.
