### ISSUE TITLE
Student Login - Leave request page remove the actions column

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#288]
remove the actions column in the leave request page
![WhatsApp Image 2023-04-08 at 10 24 34 PM](https://user-images.githubusercontent.com/30168649/230733485-6d3c6d95-238d-48c6-8627-f963a9d71e84.jpeg)

**Comment by Arunsanthoshh** [comment]
Refer the below issue and PR
https://github.com/kd-school-erp/erp-ui/issues/287
https://github.com/kd-school-erp/erp-ui/pull/330
