### ISSUE TITLE
Dashboard page left panel menu

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#292]
1. Order left panel menu based on the priority
2. Give different icons for all menus
![Screenshot 2023-04-08 224031](https://user-images.githubusercontent.com/30168649/230734243-d938eb50-4199-4387-8c4f-f1b41c13c036.jpg)

**Comment by Arunsanthoshh** [comment]
**Left pane order for ADMIN log in --**

- Dashboard
- Departments
- Subjects
- Class
- Teachers
- Students
- Staff
- Attendance
- Exams
- Fees
- Courses
- Library
- Transport
- Holiday
- Apply Leave
- Leave Request
- Events
- Notice Board
- Ask Me

**Comment by Arunsanthoshh** [comment]
**Left pane order for TEACHER login -**

- Dashboard
- Lectures
- Timetable
- Student
- Attendance
- Homework
- Exam
- Exam schedule
- Leave request
- Settings
- Ask me

**Comment by Arunsanthoshh** [comment]
**Left pane order for STUDENT login -**

- Dashboard
- Timetable
- Attendance
- Homework
- Exam
- Exam Schedule
- Leave Request
- Settings
- Ask me

**Comment by Arunsanthoshh** [comment]
**New icons updated to admin login-**
<img width="157" alt="image" src="https://user-images.githubusercontent.com/53538082/231453377-78d8034b-f761-4210-a232-462ce9ac45d2.png">
<img width="164" alt="image" src="https://user-images.githubusercontent.com/53538082/231453459-13b585d3-e94f-4642-8076-8fb98502a4db.png">
