### ISSUE TITLE
Departments super admin and admin edit delete option

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#295]
1. Need to remove the edit delete option for super admin and admin departments
2. change the student capacity field to capacity
![Screenshot 2023-04-08 230539](https://user-images.githubusercontent.com/30168649/230735290-fd387cda-b55f-4f41-864a-67a053bd9a5a.jpg)

3. change select staff to clear staff and select teacher to clear teacher
![image](https://user-images.githubusercontent.com/30168649/230762791-b83a9875-7b27-4a32-b7f7-cd348d15c5a2.png)
4. In Add Teacher,   Department dropdown does not show admin and super admin
5. In Add staff , Department dropdown does not show super admin

**Comment by kural214** [comment]
@anand-it 
change the student capacity field to capacity -- Change the field here as well.
![image](https://user-images.githubusercontent.com/44921344/231563886-e971ace0-5a09-4b44-b2cc-c26c1bf3280f.png)

**Comment by anand-it** [comment]
This Is change https://github.com/kd-school-erp/erp-ui/pull/327 This Pr @kural214 

![image](https://user-images.githubusercontent.com/36123218/231715868-4b6c86f1-7d47-475f-8d2f-9ea7e3f278d3.png)
