### ISSUE TITLE
Admin login - Student fees issues

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#311]
1. recently added record is not displayed in the Table UI
 ![image](https://user-images.githubusercontent.com/30168649/230762896-bbd39ee0-23e5-4604-a768-a5e8dba3a658.png)
2. toast message is not displaying for all operations

3. order the left panel menu to fees structure, student fee entry, student fee details
4. student fee details are not displaying
5. Dees list typo change to Fees list
![image](https://user-images.githubusercontent.com/30168649/230763296-39258e27-186f-43f1-a161-dee5d34296cd.png)
6. need to discuss about the date range( connect to kural or arun prasad)
7. Need to change excel export file name
![image](https://user-images.githubusercontent.com/30168649/230763473-0eac7ed4-69d7-4290-afa7-65c09bb26190.png)

**Comment by Gopigovind** [comment]
Hi @ArunprasadRajendran , 

1. recently added record is not displayed in the Table UI

I have checked the issue and the Fee structure year format is 2023-2024. If add the record for this format and it is working. 

![image](https://user-images.githubusercontent.com/60418235/230782680-3a333f8a-1f06-427c-a0a2-ac8e166ff2a9.png)

**Comment by ArunprasadRajendran** [comment]
@kural can you please reproduce the issue and check this one
