### ISSUE TITLE
School App entire UI functionality Testing

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#322]
School App entire UI functionality Testing

**Comment by kural214** [comment]
1. https://github.com/kd-school-erp/erp-ui/issues/321
2. https://github.com/kd-school-erp/erp-ui/issues/319
3. https://github.com/kd-school-erp/erp-ui/issues/317
4. https://github.com/kd-school-erp/erp-ui/issues/316
5. https://github.com/kd-school-erp/erp-ui/issues/315
6. https://github.com/kd-school-erp/erp-ui/issues/313
7. https://github.com/kd-school-erp/erp-ui/issues/311
8. https://github.com/kd-school-erp/erp-ui/issues/310
9. https://github.com/kd-school-erp/erp-ui/issues/309
10. https://github.com/kd-school-erp/erp-ui/issues/308
11. https://github.com/kd-school-erp/erp-ui/issues/307
12. https://github.com/kd-school-erp/erp-ui/issues/306
13. https://github.com/kd-school-erp/erp-ui/issues/302
14. https://github.com/kd-school-erp/erp-ui/issues/300
15. https://github.com/kd-school-erp/erp-ui/issues/298
16. https://github.com/kd-school-erp/erp-ui/issues/297
17. https://github.com/kd-school-erp/erp-ui/issues/296
18. https://github.com/kd-school-erp/erp-ui/issues/295
19. https://github.com/kd-school-erp/erp-ui/issues/294
20. https://github.com/kd-school-erp/erp-ui/issues/293
21. https://github.com/kd-school-erp/erp-ui/issues/292
22. https://github.com/kd-school-erp/erp-ui/issues/291
23. https://github.com/kd-school-erp/erp-ui/issues/290
24. https://github.com/kd-school-erp/erp-ui/issues/339
