### ISSUE TITLE
Access management 

### ISSUE THREAD

**Issue by kumaresan-subramani** [kd-school-erp/erp-ui#337]
![image](https://user-images.githubusercontent.com/36756050/232306693-6cef7319-8661-4f35-8227-c70585f8f06b.png)

## Descriptiom

Need to design the above Ui where multi-select has to be grouped

## API

https://github.com/kd-school-erp/erp-api/issues/172

**Comment by kural214** [comment]
@anand-it  please add department column here and show the department of the user
![image](https://user-images.githubusercontent.com/44921344/235414100-57eb9a07-7958-41a7-a5a9-7850d05fe786.png)
