### ISSUE TITLE
Admin Login Testing

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#339]
Test the entire admin login flow and notedown the issues

**Comment by ajithkumarg23** [comment]
Testing is done:
Please find below attachment for the issues.
[Admin Login Testing Issues.txt](https://github.com/kd-school-erp/erp-ui/files/11261062/Admin.Login.Testing.Issues.txt)

**Comment by ajithkumarg23** [comment]
Admin login Testing completed:
Please find below updated attachment.
[Admin Login Testing Issues.txt](https://github.com/kd-school-erp/erp-ui/files/11264408/Admin.Login.Testing.Issues.txt)
