### ISSUE TITLE
Teacher Login - Logged in teacher profile page

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#351]
1. It should automatically fill the logged in teacher details in this form and can be able to change the details by using this UI. So, need to do API integration here.
![WhatsApp Image 2023-04-18 at 10 27 29 PM](https://user-images.githubusercontent.com/30168649/232850316-291e9e86-94aa-44b0-adbb-f747478cd64f.jpeg)
![WhatsApp Image 2023-04-18 at 10 27 33 PM](https://user-images.githubusercontent.com/30168649/232850333-fa228297-5e8f-41ee-a16b-8e16502ead25.jpeg)
2. Need to show name here instead of username.
![WhatsApp Image 2023-04-18 at 10 27 51 PM](https://user-images.githubusercontent.com/30168649/232850501-d46ab0f5-820a-4e8e-8302-e37bebade2d9.jpeg)
3. This edit page not configured yet.
![WhatsApp Image 2023-04-18 at 10 28 46 PM](https://user-images.githubusercontent.com/30168649/232850696-30408fb9-3706-4c50-ae57-0c54cc96d26d.jpeg)
This is not configured in student login also
![image](https://user-images.githubusercontent.com/44921344/233758862-1d822b6a-36ed-41c9-8d47-e00c87050678.png)

**Need to ensure all the above changes in student login**

**Comment by kural214** [comment]
![image](https://user-images.githubusercontent.com/44921344/233438092-a23939ee-7a68-4614-a272-aa68be631df8.png)
1. Unable to save. Script error occurred. Ensure toaster after fixing this issue.

![image](https://user-images.githubusercontent.com/44921344/233439090-50870c12-9263-435f-8428-71b517419ceb.png)
2. In student login, you must show the student fields here. Currently, it shows teacher fields. I used kural student login (username: kural, password: kural). Please refer the admin login add student component. Need exact same form here.

![image](https://user-images.githubusercontent.com/44921344/233439623-5905b761-7fc8-444b-be45-434cd048e619.png)
3. Should not show the super admin and admin in teacher login dropdown. Please refer the admin login add teacher component. Need exact same behavior here. (username: mike, password: mike)

**Comment by ajithkumarg23** [comment]
Regarding these updated comments, @kural214 
All three logins (Admin, teacher and student) should have individual fields (some fields are only for admin and vise versa) and some data should only be visible to Admin. But here All three logins has same fields and same data. So some admin level data is also visible to teacher and students and vise versa. This is the cause for the above issues. So we need check this entire component once again from the start. Its better to create a separate ticker for this issue.
