### ISSUE TITLE
Teacher Login - Attendance page issues

### ISSUE THREAD

**Issue by ArunprasadRajendran** [kd-school-erp/erp-ui#352]
1. Post attendance API getting failed with the below payload. It showing the below failure.
[
    {
        "date": "2023-04-18T00:00:00.000Z",
        "student_id": 17,
        "first_half": "present",
        "second_half": "absent",
        "school_id": 11,
        "created_by": 78
    },
    {
        "date": "2023-04-18T00:00:00.000Z",
        "student_id": 20,
        "first_half": "null",
        "second_half": "null",
        "school_id": 11,
        "created_by": 78
    }
]
![WhatsApp Image 2023-04-18 at 10 32 44 PM (1)](https://user-images.githubusercontent.com/30168649/232851931-aeec45d5-e032-48a5-bf22-7dbac5cdc8cc.jpeg)
2. Remove the checkbox and delete button in the page
![WhatsApp Image 2023-04-18 at 10 33 12 PM](https://user-images.githubusercontent.com/30168649/232852372-47e3e2ed-54f1-44ad-b01f-ef3e1dcee0ba.jpeg)
3. In the above image date range picker showing. It should be date picker.
4.  change date range picker to month picker ref admin login http://erp-staging-app.s3-website-us-east-1.amazonaws.com/erp-ui/#/admin/students/student-attendance
![WhatsApp Image 2023-04-18 at 10 38 47 PM](https://user-images.githubusercontent.com/30168649/232852722-73b88773-a01f-415a-be1c-9fce974cdbd7.jpeg)

**Comment by kural214** [comment]
![image](https://user-images.githubusercontent.com/44921344/233433127-a164d787-45fa-429b-b04e-82a3f78e936a.png)

Duplicate records showing in the attendance sheet view. Use mike teacher login (username: mike, password: mike)

![image](https://user-images.githubusercontent.com/44921344/233433741-678998a0-fc6d-43f2-b2f9-e9f5ccabd491.png)

We can prevent the confirmation dialog for already marked stops. (No use of the confirmation dialog. It will make the same request again)

**Comment by Gopigovind** [comment]
Done, 

4. For students and teachers just show the route info based on their bus (for this we need to map bus to the teacher and student table)

Backend API is not yet implemented for this usecase and already called out @kumaresan-subramani . Once done the back end work, will implement student and teacher login

Regards,
Gopi G.

**Comment by kural214** [comment]
![image](https://user-images.githubusercontent.com/44921344/233701597-040c5dcf-6f11-4489-a529-dfee7e1717cd.png)
1. Please fix this issue in the admin login as well.

![image](https://user-images.githubusercontent.com/44921344/233701902-4f42c94f-ebb2-4f9d-a85f-f4bbfa4ae920.png)
![image](https://user-images.githubusercontent.com/44921344/233702201-f34600df-d38c-4c1d-adf0-02a5e0cfde8a.png)
2. Half circle not coming when I choose first half present and second half leave. Here Half circle should show on Rohit 21 column.

**Comment by Gopigovind** [comment]
Hi @kural214 , 

The above issue not reported in initial ticket creating, so I focused teacher login. 

Anyway, Resolved the above 2 issues. 

![image](https://user-images.githubusercontent.com/60418235/233754369-e37de9e6-9d86-4b99-82e5-051af1f101c1.png)

Regards,
Gopi G.
