### ISSUE TITLE
Teacher Login - Exams page issues

### ISSUE THREAD

**Issue by kumaresan-subramani** [kd-school-erp/erp-ui#382]
## Exams page issues

1. In dialog - need to restrict past date selection for start and end date

## Exams schedule  page issues

1. Exam schedule date has to be restricted under the selected exam date
2. newly scheduled exams are not listed on the exams schedule page - if it was created wrongly  - for get call selected date is not added in api url
![image](https://user-images.githubusercontent.com/36756050/233831472-146b1e42-80b7-4915-b529-ad97b2e7dc63.png)

3. for the duration field add hours as a lable

**Comment by Arunsanthoshh** [comment]
newly scheduled exams are not listed on the exams schedule page - if it was created wrongly - for get call selected date is not added in api url

For this query, we can create new ticket with back end and front end changes. Already confirmed with @ArunprasadRajendran 

@kural214 please review rest all things.
