### ISSUE TITLE
Teacher Login - Add New Broadcast Menu 

### ISSUE THREAD

**Issue by Jenita** [kd-school-erp/erp-ui#407]
# 1) Broadcast tab

## Add New Menu - Broadcast in Teacher and Admin login

1.  Table to Display the created broadcast, it has the below fields
     - Broadcast Title
     - broadcast Message
     - SMS
     - Call
     - Mail
     - if the call checkbox, is clicked - need to show file upload where the user can add an announcement audio file (if the call not selected, sent as null to BE)
     - Type (Bus/ Class/ All Students)
     -  If Bus - Bus Number, If Class -Class Name, If 
     -  Status
     -  Created time (Date Time)
     -  Created By - Name

2. Add a Button on the table to add a new broadcast. On Clicking add button, open the form popup to create a broadcast. A popup will have fields 
   1. Filter By Bus or Class Or All Students
   2. Filter to choose the Bus No  /Class Name/  based on 1 st filter - Disabled if All student is selected in filter1 
   3. Filter to Select Students. based on 2 nd filter
   4. Broadcast title
   5. Broadcast Message
   6. Broadcast type( Call, SMS, Mail) select Box
   7. Submit
  
On Submit, Based on Broadcast type trigger the api. Send all the student details.

# 2) Report Tab

## scope

1. add a dropdown that displays all created broadcast
2. if the user selects any, based on the selection show the report below

## Table fields

- student name
- mobile number
- call status
- sms status
- email status

**Comment by kumaresan-subramani** [comment]
## For call - API reference

**Endpoint** - https://obd37.sarv.com/api/voice/upload_announcement.php?username=u12830&token=DywG8y&announcement_path={{mp3 url}}

> Note: mp3 url must be from s3

**Sample response:**

`{"status":"success","code":"000","desc":"Announcement Uploaded Successfully","data":[{"announcement_id":"417952","announcement_name":"Sample_Voice_Recording.mp3"}]}`

![image](https://user-images.githubusercontent.com/36756050/235422012-1784bdb7-e6be-46d6-898c-4309a3f7d7a8.png)

> Note: use this announcement id for call API

**Comment by kumaresan-subramani** [comment]
## For call API

**Endpoint**

https://obd37.sarv.com/api/voice/voice_broadcast.php?username=u12830&token=DywG8y&plan_id=29945&announcement_id={{anouncement_id}}&caller_id=0&contact_numbers={{mobileNo1}}%2C{{mobileNo2}}&retry_json={"FNA":"2","FBZ":"2","FCG":"2","FFL":"2"}

> [sample API Url](https://obd37.sarv.com/api/voice/voice_broadcast.php?username=u12830&token=DywG8y&plan_id=29945&announcement_id=417952&caller_id=0&contact_numbers=8667459398%2C9789117240&retry_json={%22FNA%22:%222%22,%22FBZ%22:%222%22,%22FCG%22:%222%22,%22FFL%22:%222%22})

**Sample Response**

`{"status":"success","code":"000","desc":"Call Submitted Successfully","data":[{"contact_number":"8667459398","unique_id":"1086164_3_2498-u12830","system_api_uniqueid":"1086164_3"},{"contact_number":"9789117240","unique_id":"1086164_4_2498-u12830","system_api_uniqueid":"1086164_4"}]}`


![image](https://user-images.githubusercontent.com/36756050/235423701-2023b0ac-0244-429e-b901-25688792ab17.png)

**Comment by kumaresan-subramani** [comment]
## For call report

After calling API, as a response, we will get **unique_id**. Using that we can get the status of that specific mobile number call

**EndPoint:** 

https://obd37.sarv.com/api/voice/fetch_report.php?username=u12830&token=DywG8y&unique_ids={{unique_id}}

> [Sample Endpoint url](https://obd37.sarv.com/api/voice/fetch_report.php?username=u12830&token=DywG8y&unique_ids=1086164_4_2498-u12830)


**Sample response**

`{"status":"success","code":"000","desc":"Request Submitted Successfully","data":{"1086164_4_2498-u12830":{"status":"success","desc":"unique id fetched found","data":{"status":"Dialed","report":"Answered","contact_number":"9789117240","duration":"6","time_start":"01-May-2023 1:03:51 PM","time_connect":"01-May-2023 1:04:06 PM","time_end":"01-May-2023 1:04:12 PM","dtmf":"","currentRetryCount":0,"ivrExecuteFlow":"#1"}}}}`

**Image Reference**

![image](https://user-images.githubusercontent.com/36756050/235424270-ba0f4270-c6b6-46bb-9a78-5b766d33d4e5.png)

**Comment by Jenita** [comment]
![Image](https://user-images.githubusercontent.com/4198869/235756709-bfc8fa9b-a18b-4072-858b-9c78657694d4.png)

GET api: http://localhost:3000/api/broadcastInfo/broadcast/3
POST api: http://localhost:3000/api/broadcastInfo/broadcast
{
    "title": "Broadcast Success",
    "message": "Success Broadcast message",
    "type":"class",
    "school_id":3,
    "class_id":3,
    "created_by":3,
    "created_role":"Admin",
    "announcement_id":417952,
    "sms":1,
    "mail":1,
    "voicecall":0
}
