### ISSUE TITLE
Student Rating system

### ISSUE THREAD

**Issue by kumaresan-subramani** [kd-school-erp/erp-ui#425]
## Ui

- show class dropdown
- subject selection (based on the class selection using timetable API show subjects)
- Month selection dropdown

- Show table with below fields
   - Student Roll No
   - Student image
   - Student Name
   - class name
   - homework_completion_rating [ref](https://ej2.syncfusion.com/angular/demos/#/bootstrap5/rating/default)
   - Behavior_rating [ref](https://ej2.syncfusion.com/angular/demos/#/bootstrap5/rating/default)
   - attendance_rating [ref](https://ej2.syncfusion.com/angular/demos/#/bootstrap5/rating/default)
   - overall_rating [ref](https://ej2.syncfusion.com/angular/demos/#/bootstrap5/rating/default)
   - comments
   - month

### Note

> The overall rating will change based on all other 3 rating selecting selection and that column will be in disabled state

UI ref- http://erp-staging-app.s3-website-us-east-1.amazonaws.com/dev/#/teacher/student-attendance

**Comment by Jenita** [comment]
Post API(create and update) : http://localhost:3000/api/studentRatingInfo/studentRating 
Payload:
[{"school_id": 3,
"student_id":3,
"subject_id":6,
"class_id":3,
"month":"May-2023",
"teacher_id":3,
"homework_completion_rating":4.0,
"behavior_rating":3.0,
"attendance_rating":3.5,
"overall_rating": 3.75,
"comments": "Easliy understanding new things"}]

Get API:
http://localhost:3000/api/studentRatingInfo/studentRating/class?subjectId=6&classId=3&month=May-2023
![image](https://user-images.githubusercontent.com/4198869/236673055-a340f410-4061-45b3-a105-4787cb460ccc.png)
